PPU-fadb0af6fb7bd0113e88fb9af3eb78fe3be05d08:
  Unlock FPS:
    "Ratchet & Clank: Into the Nexus":
      BCUS99245:
        01.01:
          Enabled: true
PPU-d5041972c3464b734ed27f0b94b505a2a14471c8:
  Unlock FPS:
    Grand Theft Auto IV (Grand Theft Auto 4):
      BLUS30127:
        01.08:
          Enabled: true